apiVersion: v1
data:
  accessToken: xxx
kind: Secret
metadata:
  name: bitbucket-secret
type: Opaque
---
apiVersion: pipeline.jquad.rocks/v1alpha1
kind: PullRequest
metadata:
  name: pullrequest-bitbucket-sample
spec:
  gitProvider:
    provider: Bitbucket
    secretRef: bitbucket-secret
    bitbucket:
      restEndpoint: https://bitbucket.jquad.rocks/rest
      project: jquad
      repository: microservice
  targetBranch: 
    name: refs/heads/main
  interval: 1m
  # TODO(user): Add fields here
