# https://github.com/google/go-github/blob/master/github/pulls.go
# https://github.com/rancher/rke2/issues/2156
# https://github.com/google/go-github/blob/master/github/examples_test.go
# https://github.com/gfleury/go-bitbucket-v1
apiVersion: v1
data:
  accessToken: xxx
kind: Secret
metadata:
  name: github-secret
type: Opaque
---
apiVersion: pipeline.jquad.rocks/v1alpha1
kind: PullRequest
metadata:
  name: pullrequest-github-sample
spec:
  gitProvider:
    provider: Github
    secretRef: github-secret
    github:
      url: https://github.com/rannox/microservice.git
      owner: rannox
      repository: microservice
  targetBranch: 
    name: refs/heads/main
  interval: 10m
  # TODO(user): Add fields here
