apiVersion: v1
data:
  accessToken: xxx==
kind: Secret
metadata:
  name: github-secret
type: Opaque
---
apiVersion: pipeline.jquad.rocks/v1alpha1
kind: PullRequest
metadata:
  name: pullrequest-github-sample
spec:
  gitProvider:
    provider: Github
    insecureSkipVerify: false
    secretRef: github-secret
    github:
      url: https://github.com/
      owner: rannox
      repository: microservice
  targetBranch: 
    name: refs/heads/main
  interval: 10m
  # TODO(user): Add fields here
