apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: pullrequest-operator
  namespace: pullrequest-operator-system-build
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: git-clone
  url: https://github.com/jquad-group/pullrequest-operator.git